"""add created_at column

Revision ID: 266c8a85c4fa
Revises: 
Create Date: 2025-05-11 11:03:58.131593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '266c8a85c4fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_history')
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=500),
               nullable=False)

    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('query',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=500),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.alter_column('query',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=300),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=300),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('created_at')

    op.create_table('search_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('query', sa.VARCHAR(length=300), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_history_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
